### ISSUE TITLE
Containers not started on Ubuntu 20.10

### ISSUE THREAD

**Issue by BitcoinOG** [opendexnetwork/opendex-docker#29]
![image](https://user-images.githubusercontent.com/56045404/108500362-f3334980-72af-11eb-9610-cc5b6601083f.png)
[testnet.log](https://github.com/opendexnetwork/opendex-desktop/files/6009699/testnet.log)
[launcher.log](https://github.com/opendexnetwork/opendex-desktop/files/6009707/launcher.log)

**Comment by BitcoinOG** [comment]
This one is solved now on my ubuntu 20.10:
```
2021-02-23 17:01:34.231 [ERROR] launcher: Failed to get status: Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.40
2021-02-23 17:01:44.811 [DEBUG] utils: [run] /usr/local/bin/docker-compose ps proxy
```
and lnds are syncing fine, which I can see via the logs.

New problem: the ui shows container missing (even though lnd's are syncing and all containers are up and running):
![image](https://user-images.githubusercontent.com/56045404/108907906-01bc9080-7623-11eb-9ff2-738f2baf2618.png)
[launcher.log](https://github.com/opendexnetwork/opendex-docker/files/6031843/launcher.log)

I am suspecting this is a proxy/status issue. Please check this @Maith8Ae , if it's a ui problem we can transfer the issue back there.

**Comment by Maith8Ae** [comment]
Should be fixed by commit https://github.com/opendexnetwork/opendex-docker/commit/793dab080d4eef5c461e2d6936a613ea002ca560.

**Comment by BitcoinOG** [comment]
Solved.
